version: '3.8'

services:
  article_db:
    container_name: article_service_db
    image: postgres:${POSTGRES_VERSION:-17.4}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    restart: unless-stopped
    volumes:
      - article_postgres_data:/var/lib/postgresql/data
    networks:               
      - app-network
    ports:
      - "5432:5432"

  article_app:
    container_name: auth_service_app
    build:
      context: ../go-angular-pg/app
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      # Database
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      JWT_SECRET: ${JWT_SECRET}
      
      # SMTP
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USERNAME: ${SMTP_USERNAME}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      
      # Telegram
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      TELEGRAM_CHAT_ID: ${TELEGRAM_CHAT_ID}
      
      APP_ENV: ${APP_ENV}
    depends_on:
      - article_db
    networks:               
      - app-network
    expose:
      - "8080"

  habits_db:
    container_name: habits_service_db
    image: postgres:${POSTGRES_VERSION:-17.4}
    environment:
      POSTGRES_USER: ${HABITS_DB_USER}
      POSTGRES_PASSWORD: ${HABITS_DB_PASSWORD}
      POSTGRES_DB: ${HABITS_DB_NAME}
    restart: unless-stopped
    ports:              
      - "5433:5432"
    networks:               
      - app-network
    volumes:
      - habits_postgres_data:/var/lib/postgresql/data

  habits_api:
    container_name: habits_api
    build:
      context: ../habits-api
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      SERVER_HOST: ${HABITS_SERVER_HOST}
      SERVER_PORT: ${HABITS_SERVER_PORT}
      DB_HOST: ${HABITS_DB_HOST}
      DB_PORT: ${HABITS_DB_PORT}
      DB_USER: ${HABITS_DB_USER}
      DB_PASSWORD: ${HABITS_DB_PASSWORD}
      DB_NAME: ${HABITS_DB_NAME}
      LOGS_DIR: ${HABITS_LOGS_DIR}
      JWT_SECRET_KEY: ${HABITS_JWT_SECRET}
      JWT_EXPIRATION: ${HABITS_JWT_EXPIRATION}
      REFRESH_EXPIRATION: ${HABITS_REFRESH_EXPIRATION}
      COOKIE_DOMAIN: ${HABITS_COOKIE_DOMAIN}
      SECURE_COOKIES: ${HABITS_SECURE_COOKIES}
      APP_ENV: ${APP_ENV}
    depends_on:
      - habits_db
    networks:               
      - app-network
    expose:
      - "8080"

  habits_frontend:
    container_name: habits_frontend
    build:
      context: ../habits
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - NODE_ENV=${APP_ENV:-development}
      - VITE_API_URL=/api
    networks:               
      - app-network
    expose:
      - "80"

  article_frontend:
    container_name: article_frontend
    build:
      context: ../go-angular-pg/client
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - NODE_ENV=${APP_ENV:-development}
      - API_URL=/auth
    networks:               
      - app-network
    expose:
      - "80"

  nginx:
    image: nginx:alpine
    container_name: main_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - article_app
      - habits_api
      - article_frontend
      - habits_frontend
    restart: unless-stopped
    networks:               
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  article_postgres_data:
    name: article_postgres_data
  habits_postgres_data:
    name: habits_postgres_data
